version: '3.2'

services:
  mysql:
    build: .
    container_name: mysql-database
    ports:
      - 3306:3306
    #volumes:
      #- ./escolaire.sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: secret
      #MYSQL_DATABASE: name_db
      #MYSQL_USER: user
      #MYSQL_PASSWORD: password